name: check code every push
on: [push]

jobs:
  build:
    # Job name is check code every push
    name: check code every push
    # This job runs on Linux
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '20.x'
      - run: npm ci
      - run: npm run eslint
      - run: npm run prettier
    #   - run: npm run test
      - run: npm run build